# Generated by Django 4.0.3 on 2023-09-21 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tugas',
            old_name='dateline',
            new_name='batas_waktu',
        ),
    ]
