# Generated by Django 4.0.3 on 2023-09-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_dateline_tugas_batas_waktu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tugas',
            old_name='created_at',
            new_name='dibuat',
        ),
        migrations.RenameField(
            model_name='tugas',
            old_name='updated_at',
            new_name='diedit',
        ),
        migrations.AddField(
            model_name='tugas',
            name='selesai',
            field=models.BooleanField(default=False),
        ),
    ]
