# Generated by Django 4.0.3 on 2023-09-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_created_at_tugas_dibuat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pembayaran', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('total_pembayaran', models.IntegerField()),
                ('transaksi_pembayaran', models.IntegerField()),
            ],
        ),
    ]
