# Generated by Django 4.0.3 on 2023-09-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_total_pembayaran_pembayaran_jumlah_angsuran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='tanggal_jatuh_tempo',
        ),
    ]
