# Generated by Django 4.0.3 on 2023-10-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pembayaran_created_at_pembayaran_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
