# Generated by Django 4.0.3 on 2023-10-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_pembayaran_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='updated_at',
        ),
    ]
