# Generated by Django 4.0.3 on 2023-10-03 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_pembayaran_besar_angsuran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_pelajaran', models.CharField(max_length=250)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='materi',
            name='kelas',
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.DateField()),
                ('jam', models.TimeField()),
                ('jadwal_tambahan', models.CharField(max_length=250)),
                ('Pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pelajaran')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kelas')),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materi')),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tugas')),
            ],
        ),
    ]
