# Generated by Django 4.0.3 on 2023-10-03 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_materi_pelajaran_pelajaran_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pelajaran'),
        ),
        migrations.AlterField(
            model_name='pelajaran',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kelas'),
        ),
    ]
