# Generated by Django 4.0.3 on 2023-10-05 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_materi_pelajaran_alter_pelajaran_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='jadwal_tambahan',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='tugas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.tugas'),
        ),
    ]
