# Generated by Django 4.0.3 on 2023-10-05 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_jadwal_jadwal_tambahan_alter_jadwal_tugas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='tugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tugas'),
        ),
    ]
