# Generated by Django 4.0.3 on 2023-10-05 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_jadwal_tugas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelajaran',
            name='kelas',
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='Pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelajaran', to='app.pelajaran'),
        ),
    ]
