# Generated by Django 4.0.3 on 2023-10-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_pelajaran_kelas_alter_jadwal_pelajaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='Pelajaran',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='pelajaran',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.pelajaran'),
            preserve_default=False,
        ),
    ]
