# Generated by Django 4.0.3 on 2023-10-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_jadwal_pelajaran_jadwal_pelajaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='pelajaran',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.pelajaran'),
        ),
    ]
