# Generated by Django 4.0.3 on 2023-10-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_jadwal_pelajaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='jadwal_tambahan',
        ),
    ]
