# Generated by Django 4.0.3 on 2023-10-10 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_jadwal_jadwal_tambahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='materi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.materi'),
        ),
    ]
