# Generated by Django 4.0.3 on 2023-10-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_jadwal_materi'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='document/pdfs/%Y/%m/%d'),
        ),
    ]
